### ISSUE TITLE
znode received address needs to be controlled by Znode?

### ISSUE THREAD

**Issue by rloomba** [zcoinofficial/zcoin#138]
I'm referencing the following [https://github.com/zcoinofficial/zcoin/blob/znode/ZNODE.md](document).

In step 3, node operators are instructed to:
1. Generate znodeprivkey
2. Get a wallet address
3. Send 1000 XZC to received address

And then update a zcoin.conf file with the private key generated and transaction hash.

I'm just clarifying that the daemon running on the Znode must control the 1000 XZC? I'm a little bit concerned with sending 1000 XZC to a wallet hosted on a VPS. I would much rather keep these 1000 XZC on a wallet on an air gapped computer or paper wallet.

I'm curious to know if it's possible to hold 1000 XZC on a wallet that's different from the Znode daemon. If this is not possible, will you accept a pull request to allow this feature?

**Comment by reubenyap** [comment]
No the address you create is a new one but resides on your own wallet. The masternode 'private key' is not a key that controls the funds but merely one that starts and stops your masternode.

So the znode daemon doesn't hold your funds. Your local wallet does which you can take the usual steps to secure.

**Comment by rloomba** [comment]
@reubenyap thanks for clarifying!

Just to be extra clear, in the `znode.conf` file, the TRANSACTION HASH field, can be ANY transaction where ANY address has received 1000 XZC? The software will deduce the public address associated with this collateral transaction, and deposit all masternode rewards to this address?

**Comment by reubenyap** [comment]
Yes and it has to be in a single input with the correct index.

On 23 Nov 2017 3:07 PM, "Ryan Loomba" <notifications@github.com> wrote:

@reubenyap <https://github.com/reubenyap> thanks for clarifying!

Just to be extra clear, in the znode.conf file, the TRANSACTION HASH field,
can be ANY transaction where ANY address has received 1000 XZC? The
software will deduce the public address associated with this collateral
transaction, and deposit all masternode rewards to this address?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zcoinofficial/zcoin/issues/138#issuecomment-346543834>,
or mute the thread
