### ISSUE TITLE
Confusion about Zcoin's algorithm for mining, and Zcoin generally.

### ISSUE THREAD

**Issue by newmzy** [zcoinofficial/zcoin#180]
Hi - according to your website, lyra2z is a temporary algorithm to be used until you fork to start using "MTP". The website FAQ still says:

> MTP is currently running our testnet and is expected to go live in mid August 2017

I am, and have been for quite a while - mining Zcoin via Miningpoolhub.com using lyra2z  and I'm posting this 5 months after MTP was supposed to be implemented.

If I read recent comments on your official ANN thread here :[https://bitcointalk.org/index.php?topic=1638450.6360](url) there is a lot of FUD. To paraphrase it, people are posting that zcoin's development is not proceeding, that most of the mining is actually botnets on MPH and that zcoins's developers are just waiting to get rich off znodes.

I know what FUD is - but if I look at your FAQ on your own website, it reads like it hasn't been updated for over 6 months. Could someone please explain why I should keep mining Zcoin?

**Comment by reubenyap** [comment]
Well what happened was 2 weeks before launch a vulnerability was found in MTP by academicians. We had to stop it and fund a bounty and additional research to come up with MTPv1.2 Thank you for pointing me in updating that. It was all disclosed in the blog posts though and the faq.

**Comment by newmzy** [comment]
Do you have any comment to make about the accusations that a large portion of Zcoin mining is done by "botnets" through miningpoolhub.com?

**Comment by reubenyap** [comment]
Hi @newmzy so a lot of misinformation has been spread about this. First of all, how does this enrich the developers? It doesn't. We don't have a secret miner. Our miner was released open sourced. Of course some may accuse us of having 'secret miners software' but that's just silly. Anyone is free to develop their optimized miners. We already have our founder's reward. Secondly, if you take a look at our github, we released a major zerocoin rewrite. This doesn't enrich us in anyway, it just makes the product better.

Thirdly, how do you detect botnets? Do you judge it simply by just the number of people mining on a single entity? I have checked with MPH itself and asked him about it and he said finds the accusations strange considering on his pool, coins such as Zcash, Monero, Ethereum or even Digibyte have much larger hashrates controlled by single entities. Are they botnet controlled?

Personally mining Zcoin is still quite profitable and one of the major differences is that it favors Nvidia cards and is particularly cool and low power usage to run. Having mined many different coins, Zcoin's mining is the most stable on my setups so there may be other reasons for farms to mine them compared to other coins.

Note that many of the criticisms comes from a pool operator that used to be the number 1 pool but slowly lost market share to MPH due to inaccurate reporting stats. He made several erroneous claims which I publicly responded to and he didn't reply to those.

We even subsidized smaller pools such as Mintpond and Datapaw to get them started out but people still stick with MPH. How can the devs be faulted? Now new pools such as F2pool have also launched.
