### ISSUE TITLE
Clicking on "Subtract Fee from amount" shows incorrect behaviour

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#540]
When clicking "Subtract Fee from amount" in the Send tab, there are inconsistencies:

a) It doesn't actually subtract any fee. It makes it a free transaction.
b) The confirm send coins box actually shows it differently and shows a fee added of 0.00001 XZC instead of "Subtract Fee from amount"
c) Coin control summary actually shows it differently and shows that there is a fee of 0.00000340 XZC fee for a 340 bytes transaction.

None of these are right!

**Comment by FreakyMaryk** [comment]
@reubenyap Could you pls clarify b)
1) In case when no 'Substract fee from amount' we have next box
![image](https://user-images.githubusercontent.com/5564315/62062063-fa5bb800-b230-11e9-9c1b-467a3de75538.png)
2) In case with 'Substract fee from amount' we have next box
![image](https://user-images.githubusercontent.com/5564315/62062097-0a739780-b231-11e9-8568-218a744053db.png)

As I understand from b) on the picture 2 should be "Subtract Fee from amount" text instead of 'added as transaction fee'?
Am I right?

**Comment by reubenyap** [comment]
i think it's okay to keep the text for consistency. As long as the amount is correct.

**Comment by FreakyMaryk** [comment]
@reubenyap Okay, than approved.

**Comment by reubenyap** [comment]
Fixed on #557
