### ISSUE TITLE
Syncing speed is atrocious

### ISSUE THREAD

**Issue by bathrobehero** [zcoinofficial/zcoin#65]
In close to 3 days it only synced 9600 blocks.
In the last 16 hours the wallet synced ~100 blocks with plenty of nodes (and plenty of "PROCESS REVERSE/ERROR: CTransaction::CheckTransaction() : Error: Node does not have mint zerocoin to verify, please wait until" errors).

But, even without any errors in debug.log and after several restarts it's still painfully slow, sometimes slower than how fast new blocks being found.

If block verification really does requires this much CPU time, at least make it threaded because on 1 core it takes forever.

Win7x64, i7-6800K, SSD, 100Mbps DL.

**Comment by aizensou** [comment]
I just do a quick -reindex test with below config.

```
server=1
defaultkey=1
logtimestamps=1
dns=1
listen=1
daemon=1
rpcallowip=*
txindex=1
```

Started at 5:21 pm and now  at 2.55am I'm at block 19955. Tested on an Ubuntu 16.04 VM with 1GB RAM, 2 cores. 
`2017-02-15 01:56:58 SetBestChain: new best=384f6d137ac5dc7bcfaffd987714092a101d0ab88bfd24347289af3453b2b5eb  height=19955  log2_work=43.516667  tx=105672  date=2017-02-07 17:37:58 progress=0.839488
`

But yes we know that problem due to the verification of zerocoin txs.

Could you add these lines to your config and do a reindex and tell me whether it helps? Thanks for your patience.

`addnode=london.zcoin.io
addnode=nyc.zcoin.io
addnode=sf1.zcoin.io
addnode=xzc.suprnova.cc`

**Comment by bathrobehero** [comment]
I decided to do a full resync instead (but saved my blockchain) and it went from 1 to 2500 iun about 45 minutes. Definitely a massive improvement.

But it's stuck now and there's a bunch of block processing errors:

**Comment by ty2u** [comment]
I let this run for a few nights and it's only at 11028. Was trying to import the blockchain data from znode.io which also seems to be down now. I'm on Windows 10 on Zcoin 0.8.7.8.

**Comment by bu5hm4nn** [comment]
I also have this issue on Windows 10 x64 creators update. One improvement would be to introduce multithreading as it maxes out one core on my system when it could use 6 or 12 (if using hyperthreading).

**Comment by reubenyap** [comment]
This is now solved with the new core update.

https://github.com/zcoinofficial/zcoin/tree/core_upgrade
