### ISSUE TITLE
Move wiki to a separated site by hosting MediaWiki

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#726]
IMO wiki in GitHub is hard to use and no one take a look on it. Also it not well maintenance too. So I propose the idea that we should host MediaWiki with URL https://wiki.zcoin.io and move all wikis to there instead. This will also encourage other people to help it up to date too due to everyone can update it.

What is MediaWiki? It is a software that run https://www.wikipedia.org/

**Comment by riordant** [comment]
Sounds good, I agree with this.

**Comment by catchingknives** [comment]
One issue with our documentation is that it's spread across several places (like the wiki, our website's blog, and the FAQ on our website) so it's definitely worth thinking about having one go-to source for that.

However, I think GitHub wiki works fine and I don't see how it's hard to use. The problem is more that neither does anyone put any information there nor does anyone look for information there.

As for MediaWiki, please bear in mind that another server running another public-facing software is another server that needs to be maintained and will be attacked. 

So my view is: "yes" to a decent repository for documentation but "maybe not" to MediaWiki.

**Comment by ultimaweapon** [comment]
If it worth to have it the maintenance is not the problems. So the only thing that we need to discuss is GitHub Wiki VS MediaWiki, which I think we should vote.

**Comment by justanwar** [comment]
We should stick with what we have i.e. GitHub Wiki. Setting up another Wiki when we barely use GitHub Wiki does not make sense and will create more fragmented documentation.

**Comment by reubenyap** [comment]
I'm for maintaining Github wiki but we just need to improve the documentation here.

**Comment by qashban4** [comment]
List out ideas and places where we need improvement.

**Comment by ultimaweapon** [comment]
We should create another issue for that. I will close this now.
