### ISSUE TITLE
Automatic build Docker and publish image when release build finished

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#755]
We may try to support arm64 too due to some user request it.

**Comment by ultimaweapon** [comment]
We need #766 to be done first.

**Comment by coolcow** [comment]
Guys this is a serious problem! 

The **mandatory** 0.13.8.8 release is 2 days old, but still no docker image for it. It's not the first time that my node gets kicked of the network because the version is to old. But my docker image is up to date with the latest available (docker image) release... which is 1 month old.

For now the official docker repository should not be recommanded, or at least you should explicitly explain that this option is not suitable for production use. Please update or remove the [Running with Docker](https://github.com/zcoinofficial/zcoin#running-with-docker) part from the README until this is **really** a viable option.

**Comment by ultimaweapon** [comment]
We are really sorry for the problems. We will fix this problems now.

**Comment by ultimaweapon** [comment]
Done. Next release we will never have this issue anymore.
