### ISSUE TITLE
Coin Control totals don't get updated if you unselect UTXOs from Inputs dialog

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#784]
## Actual behaviour

![image](https://user-images.githubusercontent.com/49484468/70089776-dfd28a80-15e6-11ea-812a-2b03eab5665d.png)

## Desired behaviour
Any changes in the inputs dialogs should update the totals in the Coin Control Features box.
## Steps to reproduce
Go to spend tab under Sigma
Select some inputs
Attempt a spend that exceeds the value of the total spendable mints when you subtract 0conf ones.
Before you can confirm it will complain "The amount exceeds your balance."
Now go and unselect some inputs.
The totals in Coin Control Features get all messed up

My transaction failed with:
Source: Generated
Credit: (not accepted)
Net amount: -19.00000000 XZC
Transaction ID: a9d8d1af47fa4479c8fd1bce59217774ad08150e242d92a55ef405db094a8bc5
Output index: 0

That might be due to Sigma problem though.

**Comment by chileminer** [comment]
After playing with it , it looks like coin Fee:, After Fee: and Change   for Sigma Spend coin  control is being calculated from the Amount field for some reason, and doesn't get update when changes are made to the Amount or "Subtract fee from amount" checkbox

**Comment by riordant** [comment]
@chileminer it is by design that the Coin Control Features box is only updated after clicking "Inputs.." in that section. If the "Amount:" field is populated, it will use that in its calculation of the values. This is the same as Coin Control Features in the "Send" tab. 

Therefore to update the panel from the "Amount:" field, click "Inputs" and then "OK". The negative values are there because you have a higher "Amount:" value than outputs selected (`Insufficient Funds!`). It should not make a difference as transactions will only be allowed if they are within the correct bounds. 

That being said I am concerned that you got that transaction through the UI. Do you have extended info on the steps you used to get a transaction through with a negative net amount?

**Comment by chileminer** [comment]
Since the "Fee", "After Fee", and "Change" are calculated based on the "Amount" field then when the "Amount" entry box changes, they should be updated.   Look at the"Fee", "After Fee", and "Change" in the GUI screenshot.  There is nothing wrong with the transaction as pictured, as apparently there is another sanity check on the transaction before it is sent.    It didn't make it through the network because mints & spends were shut down.
