### ISSUE TITLE
Negative values pass verification check in verify_rangeproof

### ISSUE THREAD

**Issue by james-miller-93** [zcoinofficial/zcoin#888]
Target: `lelantus_verifier.cpp`
Severity: High, Difficulty: Low

## Description
In the Lelantus protocol, JoinSplit transactions allow for old coins to be spent, producing new coins and a transparent output value (as well as a transaction fee). As part of the transaction proof, a balancing proof is provided, which proves (in zero knowledge) that the sum of the inputs (old coins) is equal to the sum of the output coins plus the transparent output and fee. The coin values are hidden, and so range proofs, known as Bulletproofs, are provided to ensure that these values fall within an allowed range. This ensures that integer overflows cannot happen in the balancing equation (because negative commitment values are not allowed). Specifically, Bulletproofs assert that a value is between `0` and `2^n` for some parameter `n`.

In `lelantus_verifier.cpp`, the `verify` function is responsible for verifying JoinSplit proofs. Specifically, this function calls `verify_rangeproof`, which in turn calls `rangeVerifier.verify_batch`, the verification function for Bulletproofs:

```c++
bool LelantusVerifier::verify_rangeproof(
        const std::vector<PublicCoin>& Cout,
        const RangeProof& bulletproofs) {

    std::size_t n = params->get_bulletproofs_n();
    std::size_t m = Cout.size();

    while (m & (m - 1))
        m++;

    std::vector<GroupElement> g_, h_;
    g_.reserve(n * m);
    h_.reserve(n * m);
    g_.insert(g_.end(), params->get_bulletproofs_g().begin(), params->get_bulletproofs_g().begin() + (n * m));
    h_.insert(h_.end(), params->get_bulletproofs_h().begin(), params->get_bulletproofs_h().begin() + (n * m));

    std::vector<GroupElement> V;
    V.reserve(m);
    for (std::size_t i = 0; i < Cout.size(); ++i)
        V.push_back(Cout[i].getValue() + params->get_h1() * (Scalar(uint64_t(2)).exponent(params->get_bulletproofs_n()) - ::Params().GetConsensus().nMaxValueLelantusMint));

    for (std::size_t i = Cout.size(); i < m; ++i)
        V.push_back(GroupElement());

    RangeVerifier  rangeVerifier(params->get_h1(), params->get_h0(), params->get_g(), g_, h_, n);
    if (!rangeVerifier.verify_batch(V, bulletproofs))
        return false;
    return true;
}
```

However, as can be seen above, the output coins, `Cout` are first adjusted inside of `verify_rangeproof`. Specifically, the value `h1^(2^n - nMaxValueLelantusMint)` is added to the commitment. If the original output coin represented a commitment to the value `val`, adding `h1^(2^n - nMaxValueLelantusMint)` to it will produce a new commitment to the value `val + (2^n - nMaxValueLelantusMint`.

The `nMaxValueLelantusMint` variable represents the maximum allowable output per each coin. The purpose of adding the value `2^n - nMaxValueLelantusMint` was to have Bulletproofs ensure that the output coin values are less than `nMaxValueLelantusMint` (instead of just being less than `2^n`). However, the way the code is currently written has the unintended consequence of now allowing negative commitment values.

Bulletproofs assert that a value is between `0` and `2^n`. Therefore, these adjusted Bulletproofs assert that `val + (2^n - nMaxValueLelantusMint` is between `0` and `2^n`, which means that `val` can lie anywhere between `-(2^n - nMaxValueLelantusMint)` and `nMaxValueLelantusMint`, and thus it can be negative.

This is very problematic as now the balance equation can now overflow. If this occurs, coins can be created out of thin air.

## Exploit Scenario
An attacker Eve recognizes this flaw and creates a JoinSplit transaction with output coins that have negative values. The negative values cause an overflow to occur in the balance equation, and it still verifies, but coins are created out of thin air.

## Recommendation
Add the original output coin commitments to the vector `V` that will be input into `verify_batch`, and keep the adjusted commitments. If both the original and adjusted commitments pass verification, this proves that the commitment value is between `0` and `nMaxValueLelantusMint`, as intended.

**Comment by reubenyap** [comment]
It is important for us to give context as to how this bug came about.

The initial Lelantus cryptographic library that we handed for audit to Trail of Bits was reviewed to the best of our ability by our team. ToB's primary focus was to audit the cryptographic library we provided.

Lelantus integration code was at the time of audit still being written and was a work in progress which was unreviewed by other members of the team or even the author of the code.

During the course of the audit, ToB raised a query as to where we limited the max amounts of Lelantus mints as it was not present in the cryptographic library provided or the branch they were auditing. The idea of limiting a max Lelantus mint amount is to prevent mints from being too large that may affect anonymity when spent so the decision was to limit it to a total max mint amount of 1001 XZC per mint.

To answer ToB's query, the WIP unreviewed integration code was merged into the audit review branch as we wanted to assist the ToB audit before they concluded the audit period. Both the Zcoin team and ToB were trying for as much audit coverage as possible in the given time of 2 engineer weeks. This however resulted in this obvious error of a missing range proof to check for negative values to creep in which would have normally not been possible due to our standard practice of having two other team members with cryptographic knowledge to check any PR touching cryptographic portions before it is merged. We are also confident that it would have been caught upon the author of the code reviewing his own work before making a PR.

This was however an important reminder though to not deviate from our standard approval processes. The fix for this is located on this [commit](https://github.com/zcoinofficial/zcoin/commit/1bc6510a8ce48408fcae336c95f6c801b8155bca) where we add the missing range proof.
